// Generated by CoffeeScript 1.10.0
(function() {
  var a, b, c, x, y;

  x = 1 + 1;

  y = 1 + 1;

  "foo".concat("barbaz").replace("foobar", "fubar");

  a = 1;

  b = 2;

  c = 2;

  window.me = 'remous';

  y = 3;


  /*
  x = 4
   */

}).call(this);
