// Generated by CoffeeScript 1.10.0
(function() {
  var DateNowFn, DateNowResult;

  console.log("hello world!");

  console.log("hello");

  DateNowFn = Date.now;

  DateNowResult = Date.now();

  Math.max(2, 3, Math.min(4, 5, 6));

  Math.max(2, 3, Math.min(4, 5, 6));

}).call(this);
