// Generated by CoffeeScript 1.10.0
(function() {
  var threeSquared;

  Math.max(2, 3, Math.min(4, 5, 6));

  Math.max(2, 3, Math.min(4, 5, 6));

  Math.max(2, 3, Math.min(4, 5, 6));

  threeSquared = Math.pow(3, Math.floor(Math.min(4, Math.sqrt(5))));

  threeSquared = Math.pow(3, Math.floor(Math.min(4, Math.sqrt(5))));

}).call(this);
