// Generated by CoffeeScript 1.10.0
(function() {
  var day, number;

  if (true === true) {
    console.log("remous");
  }

  if (true === true) {
    console.log('hehe');
  }

  if (true === true) {
    console.log(1);
  }

  console.log('没有缩进');

  number = 6;

  console.log("Let's test our number");

  if (number > 5) {
    console.log("Our number is greater than 5");
    if (number > 10) {
      console.log("Our number is greater than 10");
    }
    console.log("Now we're done testing");
  }

  number = -8;

  if (number > 0) {
    "Positive";
  } else if (number < 0) {
    "Negative";
  } else {
    "Zero";
  }

  day = "Monday";

  if (day[0] !== "S") {
    console.log("This is a weekday.");
  }

  day = "Monday";

  if (day[0] !== "S") {
    console.log("This is a weekday");
  } else {
    console.log("It's the weekend");
  }

  if (true === true) {
    console.log("Truth achieved");
  }

  if (true !== true) {
    console.log("Universe Error");
  }

}).call(this);
