// Generated by CoffeeScript 1.10.0
(function() {
  var blurryPhoto, hairy, isBigfoot, location, manInApeSuit, mute, playingMusic, power, reactor, status;

  1 === 2;

  3 !== 4;

  if (1 < 2 && 3 >= 2) {
    if (false || true) {
      if (!false) {
        console.log("All is well.");
      }
    }
  }

  status = 'normal';

  reactor = 'primed';

  if (status === 'normal') {
    console.log('All clear');
  }

  if (reactor !== 'primed') {
    console.log('Abort mission');
  }

  location = "Washington";

  hairy = false;

  blurryPhoto = true;

  manInApeSuit = false;

  isBigfoot = location === "Washington" && (hairy || blurryPhoto) && !manInApeSuit;

  power = true;

  mute = false;

  if (power === true) {
    if (mute === false) {
      playingMusic = true;
    }
  } else {
    playingMusic = false;
  }

}).call(this);
