// Generated by CoffeeScript 1.10.0
(function() {
  var bigNumber, countdown, end, i, languages, results, singleDigits, start;

  languages = ["english", "spanish", "french"];

  console.log(languages[1]);

  languages = ["english", "spanish", "french"];

  singleDigits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  countdown = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1];

  [1, 2, 3, 4, 5] === [1, 2, 3, 4, 5];

  [1, 2, 3, 4] === [1, 2, 3, 4];

  start = 2;

  end = 9;

  bigNumber = (function() {
    results = [];
    for (var i = start; start <= end ? i <= end : i >= end; start <= end ? i++ : i--){ results.push(i); }
    return results;
  }).apply(this);

}).call(this);
