// Generated by CoffeeScript 1.10.0
(function() {
  var animal, animals, evenNumbers, i, j, k, l, len, len1, len2, len3, n, planet, plantIndex, pluralAnimals, solarSystem, word, words;

  animals = ["dog", "cat", "bird"];

  for (i = 0, len = animals.length; i < len; i++) {
    animal = animals[i];
    console.log(animal);
  }

  for (j = 0, len1 = animals.length; j < len1; j++) {
    animal = animals[j];
    console.log(animal);
  }

  pluralAnimals = (function() {
    var k, len2, results;
    results = [];
    for (k = 0, len2 = animals.length; k < len2; k++) {
      animal = animals[k];
      results.push(animal + 's');
    }
    return results;
  })();

  pluralAnimals = (function() {
    var k, len2, results;
    results = [];
    for (k = 0, len2 = animals.length; k < len2; k++) {
      animal = animals[k];
      results.push(animal + 's');
    }
    return results;
  })();

  words = ["dogma", "catasrophe", "doggerel", "hangdog"];

  for (k = 0, len2 = words.length; k < len2; k++) {
    word = words[k];
    if (word.indexOf("dog") !== -1) {
      console.log(word);
    }
  }

  evenNumbers = (function() {
    var l, results;
    results = [];
    for (n = l = 1; l <= 100; n = ++l) {
      if (n % 2 === 0) {
        results.push(n + 'is even');
      }
    }
    return results;
  })();

  solarSystem = ["Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"];

  for (plantIndex = l = 0, len3 = solarSystem.length; l < len3; plantIndex = ++l) {
    planet = solarSystem[plantIndex];
    if (planet !== "Pluto") {
      console.log("Planet #" + (plantIndex + 1) + " is " + plant);
    }
  }

  evenNumbers = (function() {
    var m, results;
    results = [];
    for (n = m = 2; m <= 100; n = m += 2) {
      results.push(n);
    }
    return results;
  })();

}).call(this);
