// Generated by CoffeeScript 1.10.0
(function() {
  var authorsBicycle, authorsBicycle1, key, value;

  authorsBicycle = {
    color: 'black',
    fenders: true,
    gears: 24
  };

  authorsBicycle1 = {
    color: 'black',
    brand: {
      make: "Surly",
      model: "Cross Check"
    },
    fenders: true,
    gears: 25
  };

  for (key in authorsBicycle) {
    value = authorsBicycle[key];
    console.log("Key: " + key + " Value: " + value);
  }

}).call(this);
