// Generated by CoffeeScript 1.10.0
(function() {
  var availablePets, nameElement, pet, petOutput, shop;

  shop = {
    owner: {
      name: "Ian"
    },
    animals: [
      {
        name: "Kelsey",
        type: "dog"
      }, {
        name: "Sgt. Snuffles",
        type: "dog"
      }, {
        name: "Chomps",
        type: "rabbit"
      }, {
        name: "Flops",
        type: "rabbit"
      }, {
        name: "Bopper",
        type: "rabbit"
      }, {
        name: "Chairman Meow",
        type: "cat"
      }, {
        name: "Jacques",
        type: "cat"
      }, {
        name: "Chupa",
        type: "cat"
      }, {
        name: "Alfred",
        type: "horse"
      }
    ]
  };

  nameElement = document.getElementById("owner-name");

  nameElement.innerHTML = shop.owner.name;

  document.title = shop.owner.name + "'s Pet Shop";

  petOutput = (function() {
    var i, len, ref, results;
    ref = shop.animals;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      pet = ref[i];
      results.push("<li>" + pet.name + "</li>");
    }
    return results;
  })();

  availablePets = document.getElementById("available_pets");

  availablePets.innerHTML = petOutput.join(" ");

}).call(this);
