// Generated by CoffeeScript 1.10.0
(function() {
  var animalSound, availablePets, formatPetDescription, formatPetName, i, nameElement, pet, petOutput, shop;

  shop = {
    owner: {
      name: "Ian"
    },
    animals: [
      {
        name: "Kelsey",
        type: "dog",
        breed: "Kelsey",
        description: "this is Kelsey"
      }, {
        name: "Sgt. Snuffles",
        type: "dog",
        breed: "Sgt. Snuffles",
        description: "this is Sgt. Snuffles"
      }, {
        name: "Chomps",
        type: "rabbit",
        breed: "Chomps",
        description: "this is Chomps"
      }, {
        name: "Flops",
        type: "rabbit",
        breed: "Flops",
        description: "this is Flops"
      }, {
        name: "Bopper",
        type: "rabbit",
        breed: "Bopper",
        description: "this is Bopper"
      }, {
        name: "Chairman Meow",
        type: "cat",
        breed: "Chairman Meow",
        description: "this is Chairman Meow"
      }, {
        name: "Jacques",
        type: "cat",
        breed: "Jacques",
        description: "this is Jacques"
      }, {
        name: "Chupa",
        type: "cat",
        breed: "Chupa",
        description: "this is Chupa"
      }, {
        name: "Alfred",
        type: "horse",
        breed: "Alfred",
        description: "this is Alfred"
      }
    ]
  };

  nameElement = document.getElementById("owner_name");

  nameElement.innerHTML = shop.owner.name;

  document.title = shop.owner.name + "'s Pet Shop";

  animalSound = function(animal) {
    switch (animal.type) {
      case "cat":
        return "meow";
      case "dog":
        return "bark";
      case "horse":
        return "donkey";
      default:
        return "sniff sniff";
    }
  };

  formatPetName = function(pet) {
    return pet.name + " <span class='sound'>" + (animalSound(pet)) + "!</span>";
  };

  petOutput = (function() {
    var j, len, ref, results;
    ref = shop.animals;
    results = [];
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      pet = ref[i];
      results.push("<li><a href='#' onclick='selectPet(" + i + ", this)'>" + (formatPetName(pet)) + "</a></li>");
    }
    return results;
  })();

  availablePets = document.getElementById("available_pets");

  availablePets.innerHTML = petOutput.join(" ");

  formatPetDescription = function(pet) {
    return ("<h2>" + pet.name + "</h2>") + ("<h3 class='breed'>" + pet.breed + "</h3>") + ("<p class='description'>" + pet.description + "</p>");
  };

  window.selectPet = function(petIndex, element) {
    var j, len, link, petInfo, ref;
    pet = shop.animals[petIndex];
    petInfo = document.getElementById("pet_information");
    petInfo.innerHTML = formatPetDescription(pet);
    ref = document.querySelectorAll("#available_pets a");
    for (j = 0, len = ref.length; j < len; j++) {
      link = ref[j];
      link.className = "";
    }
    return element.className = "selected";
  };

}).call(this);
