// Generated by CoffeeScript 1.10.0
(function() {
  var operators, verb;

  verb = "build";

  operators = "bracket enclosures";

  console.log("You " + verb + " string using " + operators);

  console.log((1 + 1) + "'s company, " + (1 + 2) + " is a crowd");

  console.log("A googol is a large number: " + (Math.pow(10, 100)));

  console.log("No problems " + ("here".toUpperCase()) + "!");

}).call(this);
