// Generated by CoffeeScript 1.10.0
(function() {
  var result;

  switch (iSpy) {
    case "sky":
      console.log("blue");
      break;
    case "grass":
      console.log("green");
      break;
    default:
      console.log("gray");
  }

  switch (iSpy) {
    case "sky":
      console.log("blue");
      break;
    case "grass":
      console.log("green");
      break;
    default:
      console.log("gray");
  }

  switch (iSpy) {
    case "sky":
    case "lake":
      console.log("blue");
      break;
    case "grass":
    case "frog":
    case "stoplight":
      console.log("green");
      break;
    default:
      console.log("gray");
  }

  result = (function() {
    switch (iSpy) {
      case "sky":
      case "lake":
        return console.log("blue");
      case "grass":
      case "frog":
      case "stoplight":
        return console.log("green");
      default:
        return console.log("gray");
    }
  })();

}).call(this);
