// Generated by CoffeeScript 1.10.0
(function() {
  var alpha, animalStatus, briefcase, oppositeMath, ref, ref1, tree, ufosExist, wasabducted;

  if (typeof yeti !== "undefined" && yeti !== null) {
    console.log("i want to believe");
  }

  animalStatus = function(animal) {
    var ceratures;
    ceratures = {
      ocelot: true,
      dodo: false
    };
    if (ceratures[animal] != null) {
      if (ceratures[animal] != null) {
        return console.log("The " + animal + " is alive and well");
      } else {
        return console.log("Oh no! The " + animal + " is extinct!");
      }
    } else {
      return console.log("The " + animal + " isn't real.");
    }
  };

  if ((typeof hat !== "undefined" && hat !== null) && (typeof mittens !== "undefined" && mittens !== null) && (typeof boots !== "undefined" && boots !== null)) {
    console.log("Ok");
  }

  tree = {
    pine: {
      type: "evergreen"
    },
    crabapple: {
      type: "deciduous",
      fruit: {
        edible: false
      }
    }
  };

  if ((ref = tree.pine.fruit) != null ? ref.edible : void 0) {
    console.log("Mmmm...truffula fruit");
  }

  alpha = {
    lowercase: ['a', 'b', 'c', 'd']
  };

  console.log((ref1 = alpha.lowercase) != null ? ref1[2].toUpperCase() : void 0);

  oppositeMath = {
    min: Math.max
  };

  console.log(typeof oppositeMath.min === "function" ? oppositeMath.min(3, 2, 5) : void 0);

  console.log(typeof oppositeMath.max === "function" ? oppositeMath.max(3, 2, 4) : void 0);

  briefcase = {
    color: "silver"
  };

  if (briefcase.conbination == null) {
    briefcase.conbination = "1234";
  }

  if (briefcase.color == null) {
    briefcase.color = "black";
  }

  console.log(briefcase);

  wasabducted = "aa";

  ufosExist = "aaa";

  ufosExist || (ufosExist = wasabducted);

  ufosExist || (ufosExist = wasabducted);

}).call(this);
